### ISSUE TITLE
订单查询那里无效

### ISSUE THREAD

**Issue by pacmanzou** [haoran-mc/CanteenOrdering#7]
![](https://cdn.jsdelivr.net/gh/pacmanzou/pictures@main/16522513577511652251357036.png)

**Comment by haoran-mc** [comment]
记得当时没有实现这个功能，

**Comment by pacmanzou** [comment]
![](https://cdn.jsdelivr.net/gh/pacmanzou/pictures@main/16522770799561652277079235.png)

![](https://cdn.jsdelivr.net/gh/pacmanzou/pictures@main/16522769339051652276933183.png)

点击那个搜索button时，我打印了OrdersRecord.vue里data里面的this.queryInfo.query, 这个值就是我想要的，但是我不知道该如何在后台获取到它的值，我刚学习vue和gin，不知道该怎么获取，试了很久也不行，可以实现一下这个功能吗？如果有时间的话，谢谢。

**Comment by haoran-mc** [comment]
因为你没有把 this.queryInfo.query 这个值传到后端，你的 OrdersRecord.vue 第 88 行应该这样写：

```
this.$http.get(`ordersRecordSearch/${this.queryInfo.query}`).then(res => {
```

搜索历史订单的功能我实现并提交了，简单的测试了一下，应该没问题。

**Comment by pacmanzou** [comment]
ok，感谢
